package com.bfmatch.api.notification

enum class NotificationType {
    INVITE_ACCEPTED,
    INVITE_DECLINED,
    MEMBER_JOINED,
    MEMBER_KICKED,
    MEMBER_ROLE_CHANGED,
    GROUP_UPDATED,
    GROUP_CLOSED,
    GROUP_REMINDER,
    GRADE_UPGRADED,
    GAME_CREATED,
    GAME_CANCELLED,
    GAME_STARTED,
    GAME_COURT_CHANGED,
    GAME_FINISHED,
    GAME_PROPOSAL_RECEIVED,
    GAME_PROPOSAL_APPROVED,
    GAME_PROPOSAL_REJECTED,
    GAME_SCORE_REQUESTED,
    GAME_SCORE_CONFIRMED,
    GAME_SCORE_REJECTED,
}
